### PR TITLE
Update to 2018-12 target platform

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by akurtakov** [comment]
@mickaelistria Please review as there is change in TestLSPIntegration which I think is good one but second pair of eyes wouldn't hurt.

**Comment by mickaelistria** [comment]
The test failure seems to show that either latest LSP4E or RLS doesn't manage to place the error marker properly. This needs more investigation before we merge it.

**Comment by mickaelistria** [comment]
To ease progress,  I suggest you separate the metadata/Maven updates and the TP updates in different PRs so we'll be able to merge at least a part of this work safely.

**Comment by akurtakov** [comment]
Maven fixes are in and target update part is to be handled in #194

**Pull request closed without merging**
