### PR TITLE
Update to README.md

### PR DESCRIPTION
**Pull request by LucasBullen**
- Make the landing page more presentable
 - Installation instructions updated to reflect Issue #104

Signed-off-by: lbullen <lbullen@redhat.com>

### CODE REVIEW

**Comment by LucasBullen** [comment]
@mickaelistria as it may land on you to update the links, like the idea of having direct links to the package download? Makes it easier to give new users instructions to install Corrosion.

**Comment by mickaelistria** [comment]
Have you tried achieving a similar result sticking to markdown?

**Comment by mickaelistria** [comment]
Have you tried achieving a similar result sticking to markdown?

**Comment by mickaelistria** [comment]
About the link, I think we can give the single link http://www.eclipse.org/downloads/packages/release/photon/r/eclipse-ide-rust-developers-includes-incubating-components

**Comment by LucasBullen** [comment]
Replaced the table with the single link. Unable to centre titles with plain markdown and I feel like it adds to the page.

**Comment by mickaelistria** [comment]
The issue with html in placeof markdown is that it's not as easy to read
when not rendered. I tend to believe that simplicity and plain text
readability areore important than fancy visual and layout.

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by LucasBullen** [comment]
Been playing around with this for a bit and I'm going to disagree. GitHub README files are not meant to be viewed unrendered and in our case this is a marketing issues. We need the first impression of Corrosion to
 - Stand out
 - Show logo
 - Keep users on the page to ultimately...
 - Be downloaded

It may be small here but we should not restrict ourselves to the visual look of the code when it interferes with possible user acquisition.

**Comment by mickaelistria** [comment]
If the goal is to get users, then allthat doesn't matter. Make a video and
an install link. The name and logo are noise too ;)


-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by LucasBullen** [comment]
Removed all html

**Pull request merged**
