### PR TITLE
Fix #202 - Cannot use Rust if installed in directories containing spaces

### LINKED ISSUE #202: Cannot use Rust if installed in directories containing spaces
I have found that should rust be installed in a directory containing spaces, then corrosion will not be able to use the rust installation.

To give my specific example. I am using Windows 10 X86_64. The user directory is "C:\users\Michael Whapples\". I had installed rust using rustup, letting it install in the default location under the user home directory. When I tried to use corrosion, when I went to preferences to configure the rust paths, I found even when the rust installation directories had been explicitly set there was still an error message about not being able to use rust (cannot remember the exact error message, either not being able to find the executable or obtain version information) and the apply button was not available.

I realised that the space in the directory path may have been causing problems, so I uninstalled rust, set RUSTUP_HOME and CARGO_HOME to a path without spaces (eg. "C:\rust\") and reinstalled rust via rustup. Using corrosion with rust installed in a location without spaces in the path worked fine.

At the moment I have only been able to test this issue on Windows, it may or may not exist on other platforms.

### PR DESCRIPTION
**Pull request by justdak**
Signed-off-by: Dmitry Kudryavtsev <dmitry.kudryavtsev@arsysop.ru>

### CODE REVIEW

**Comment by justdak** [comment]
For more information, please see https://github.com/eclipse/corrosion/issues/202#issuecomment-450530104

- I changed **getProcessForCommand** function code to handle parameters with spaces correctly.

- I had to overload the **getProcessForCommand** method to use it with complex command in **isRustupSectionValid**:
image

**Comment by norru** [comment]
@mickaelistria Is using https://commons.apache.org/proper/commons-exec/ an option?

**Comment by norru** [comment]
`apache-commons-exec` seems to work fine for me:

```
package org.eclipse.corrosion.tests;

import java.io.IOException;

import org.apache.commons.exec.CommandLine;
import org.apache.commons.exec.DefaultExecutor;
import org.apache.commons.exec.ExecuteException;
import org.junit.Test;

public class CommonsExecTest {
	@Test
	public void testCommandLineBuild() throws ExecuteException, IOException {
		// touch seems to work fine, path is resolved
		final CommandLine cmd1 = new CommandLine("touch");
		cmd1.addArgument("a");
		cmd1.addArgument("b");
		cmd1.addArgument("c");
		cmd1.addArgument("this contains spaces", false);
		new DefaultExecutor().execute(cmd1);
		System.out.println(String.join(" ", cmd1.toStrings()));

		// bash -c caveat
		final CommandLine cmd3 = new CommandLine("/bin/bash");
		cmd3.addArgument("-c");
		cmd3.addArgument("ls a b c", false);
		cmd3.addArgument("this contains spaces", false); // this option is ignored by bash -c
		System.out.println(String.join(" ", cmd3.toStrings()));
		new DefaultExecutor().execute(cmd3);

		// direct ls execution
		CommandLine cmd2 = new CommandLine("ls");
		cmd2.addArgument("a");
		cmd2.addArgument("b");
		cmd2.addArgument("c");
		cmd2.addArgument("this contains spaces", false);
		cmd2.addArgument("d"); // this one makes it fail
		System.out.println(String.join(" ", cmd2.toStrings()));

		try {
			new DefaultExecutor().execute(cmd2);
		} catch (Exception e) {
			// should throw as the file is not found
			e.printStackTrace();
		}

		// This gets it right
		final CommandLine cmd4 = new CommandLine("ls");
		cmd4.addArgument("a");
		cmd4.addArgument("b");
		cmd4.addArgument("c");
		cmd4.addArgument("this contains spaces", false);
		System.out.println(String.join(" ", cmd3.toStrings()));
		new DefaultExecutor().execute(cmd3);
	}
}
```

**Comment by justdak** [comment]
Hi @norru, thank you for quick response and assistance. I hope we can fix this issue together. :)

I can see that you already analyze my implementation correctly. Anyway, let me explain this fix in details.
The main change is this line of code in **getProcessForCommand** method: 

image

For example, without this change, **ProcessBuilder** will have the following arguments:
command[0] = "cmd";
command[1] = "/c";
command[2] = "C:/users/Michael Whapples/.cargo/bin/rustup --version";

And **builder.start()** will have empty response.

I changed **getProcessForCommand** method to handle parameters with spaces correctly:
command[0] = "cmd";
command[1] = "/c";
command[2] = "C:/users/Michael Whapples/.cargo/bin/rustup";
command[3] = "--version"";

There is still oportunity to have bash -c "a b c" instead bash -c a b c. It depends on arguments of **validateCommandVersion** function: 
- getOutputFromCommand(new String[]{"a", "b" "c"})  // bash -c "a b c"
- getOutputFromCommand(new String[]{"a b c"}) // bash -c a b c

Do you agree?

**Comment by norru** [comment]
Hi @justdak. Your implementation will probably work fine in **Windows** using **cmd** but won't work in Linux/U*x using via bash.

This is because the argument of `bash -c` **must** be a *single string* which concatenates the exec with his args, while `cmd /c` accepts multiple strings so the first one can be the executable and the subsequent one can be its args.

Taking from your example
```
command[0] = "cmd";
command[1] = "/c";
command[2] = "C:/users/Michael Whapples/.cargo/bin/rustup";
command[3] = "--version"";
```
The following **will likely not work** in Linux as `bash -c` will ignore `command[3]`:
```
command[0] = "bash";
command[1] = "-c";
command[2] = "/home/Michael Whapples/.cargo/bin/rustup";
command[3] = "--version"";
```

The following **will** work. As you see, `command[2]` and `command[3]` are joined together into one argument command[2] which contains the first **quoted** string (because it contains spaces) and the second unquoted. 

```
command[0] = "bash";
command[1] = "-c";
command[2] = "\"/home/Michael Whapples/.cargo/bin/rustup\" --version";
```

So for this solution to work you have to do **two** things:

1) your solution has to be restricted to Windows implementation
2) you need to restore the old behaviour for the Lunix branch and, *on top of it*, in order to fix the original problem in Linux as well, you need to change the way the arguments are concatenated so they're quoted correctly if they contain spaces or other control characters. This is not as trivial as it seems -  there are a bunch of thorny corner cases around handling arguments which may contain spaces, single quotes, double quotes, escaped quotes in various levels of nesting, slashes and backslashes.

There are libraries such as `commons-exec` which abstract the underlying `exec` implementation if we don't want to reinvent the wheel.

**Comment by norru** [comment]
Hi @justdak, that's brilliant! Thanks so much for finding the time to install and test on Ubuntu as well as Windows!

@mickaelistria pointed out that there could be a catch that `ProcessBuilder` *might* not resolve the `%PATH%` properly, so this needs a bit more testing, especially on Windows. I will give Linux a spin now.

Said that, this solution is likely to work fine in our case above as we're specifying the whole path to `rustup` and `cargo` - but the same `getProcessForCommand` might be used elsewhere in contexts when the full path is not available and it's resolved using the system's `PATH` env var.

If this is confirmed to work in both Windows and Linux, it would be my preferred approach by far.

**Comment by norru** [comment]
```java
	private static int runAndWait(String... args) throws InterruptedException, IOException {
		final ProcessBuilder cmd1 = new ProcessBuilder(args).inheritIO();
		System.out.println(cmd1.command());
		return cmd1.start().waitFor();
	}

	@Test
	public void testProcessBuilderBuild() throws ExecuteException, IOException, InterruptedException {
		// touch seems to work fine, path is resolved
		runAndWait("rls", "--version");
		runAndWait("/home/nico/Program Files/rls", "--version");
		runAndWait("ls with spaces", "-l");
		runAndWait("touch", "a", "b", "c", "this contains spaces");
		runAndWait("/bin/bash", "-c", "ls a b c", "this contains spaces");
		runAndWait("ls", "a", "b", "c", "this contains spaces", "d");
		runAndWait("ls", "a", "b", "c", "this contains spaces");
	}
```

```
[rls, --version]
rls-preview 1.31.6 (bd5b899 2018-12-10)
[/home/nico/Program Files/rls, --version]
rls-preview 1.31.6 (bd5b899 2018-12-10)
[ls with spaces, -l]
total 32
-rw-r--r-- 1 nico nico    0 Jan  1 23:08 a
-rw-r--r-- 1 nico nico 1412 Dec  5 20:19 about.html
-rw-r--r-- 1 nico nico    0 Jan  1 23:08 b
-rw-r--r-- 1 nico nico  218 Dec  5 20:19 build.properties
-rw-r--r-- 1 nico nico    0 Jan  1 23:08 c
drwxr-xr-x 2 nico nico 4096 Nov 30 22:14 META-INF
drwxr-xr-x 3 nico nico 4096 Jul 28 14:17 OSGI-INF
-rw-r--r-- 1 nico nico 1416 Nov 30 22:14 pom.xml
drwxr-xr-x 5 nico nico 4096 Jul 28 14:17 projects
drwxr-xr-x 3 nico nico 4096 Jul 28 14:17 src
drwxr-xr-x 6 nico nico 4096 Dec  3 20:12 target
-rw-r--r-- 1 nico nico    0 Jan  1 23:08 this contains spaces
[touch, a, b, c, this contains spaces]
[/bin/bash, -c, ls a b c, this contains spaces]
a
b
c
[ls, a, b, c, this contains spaces, d]
a
b
c
this contains spaces
[ls, a, b, c, this contains spaces]ls: cannot access 'd': No such file or directory

a
b
c
this contains spaces

```

**Comment by norru** [comment]
@mickaelistria Can you please help with the CI? It does appear to be stuck.

**Comment by norru** [comment]
Reading around, user.dir is frowned upon (but likely work). While I am nitpicking there seems to be a more appropriate solution. Can you try:

Paths.get("").toAbsolutePath()

**Comment by mickaelistria** [comment]
OK, or maybe another reason why `bin/bash` or `cmd` can be necessary (but isn't here) is for files that aren't binary files but files to be interpreted with a `#!/bin/python` header or similar.
Since it's not the case for `rustup`, it's all fine to just get rid of it.

**Comment by norru** [comment]
>  is for files that aren't binary files but files to be interpreted with a #!/bin/python header or similar.

Right, in that case we can still run `python` or `bash` as the executable and provide the script's path as a parameter, on a case-by-case.

I would go for the `bash`-less implementation by @justdak - the only nit remaining was related to getting the current `pwd` but I think it's trivial to solve.

**Comment by norru** [comment]
@justdak, can you confirm this bit works on Windows?

```getOutputFromCommand((Platform.getOS().equals(Platform.OS_WIN32) ? "where" : "which"), "gdb"))```

if not, you could still invoke it as 

```getOutputFromCommand("cmd", "/c", "where", "gdb"))```

on Windows (rejigging the ternary operator into an `if ()` branch)

**Comment by justdak** [comment]
@norru Looks like that `Paths.get("").toAbsolutePath().toString()` works both on Windows and Linux.

I noticed the problem with case sensitive while testing `getOutputFromCommand((Platform.getOS().equals(Platform.OS_WIN32) ? "where" : "which"), "gdb"))` on Windows:

image

So I changed it to `envVariables[i].toUpperCase().startsWith("PATH=")`. Do you agree with it?

And to test `where gdb` command, I had to add msys64\mingw64\bin folder to the PATH env var.

image

As you see on screenshot, it works on Windows.

**Comment by norru** [comment]
Hi @justdak, looks good. I'm not fully convinced about the bit that builds the path variable as, again, there is something to think through with regards to quotes and special characters, but I think it's out of the scope of this changelist - we may have to revisit later.

I would suggest @mickaelistria merge this change in and pushes a build to Snapshots so we can test it in real life.

**Comment by mickaelistria** [comment]
> I would suggest @mickaelistria merge this change in and pushes a build to Snapshots so we can test it in real life.

At your service ;)

**Comment by justdak** [comment]
@norru @mickaelistria Thank you guys for assistance!

**Comment by norru** [comment]
I've got latest Corrosion snapshot and so far I have not seen any horrible breakage ;) Fingers crossed.

**Pull request merged**
