### PR TITLE
Add console hyperlinks for errors.

### LINKED ISSUE #132: Linkable/clickable file paths from Cargo output in Console
Even if the RLS does it in the background, It would be great to have the output parsed in the Console (for cargo build and cargo run) so that file names and line numbers are transformed into clickable links, for instance:

```
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
```

```
warning: where clauses are not enforced in type aliases
  --> src/main.rs:58:2
   |
58 |     D: gfx::Device,
   |     ^^^^^^^^^^^^^^
   |
```

### PR DESCRIPTION
**Pull request by akurtakov**
Fixes #132

Signed-off-by: Alexander Kurtakov <akurtako@redhat.com>

### CODE REVIEW

**Comment by norru** [comment]
Hi, just got latest Corrosion (not sure whether it contains this changelist) and I get the following error on build

```
An internal error occurred during: "Match Job".
Path for project must have only one segment.
```

**Comment by akurtakov** [comment]
Can you share a reproducer ?

**Comment by norru** [comment]
is `Corrosion: Rust edition in Eclipse IDE	0.4.2.201907112000` up to date?

**Comment by norru** [comment]
`cargo test --no run` Corrosion run test configuration for https://github.com/itadinanta/rust-oids spits out the following TTY on console, and spits 3 instances of this error

```
java.lang.IllegalArgumentException: Path for project must have only one segment.
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.resources.WorkspaceRoot.getProject(WorkspaceRoot.java:150)
	at org.eclipse.corrosion.ErrorLineMatcher.matchFound(ErrorLineMatcher.java:63)
	at org.eclipse.ui.internal.console.PatternMatchListener.matchFound(PatternMatchListener.java:44)
	at org.eclipse.ui.internal.console.ConsolePatternMatcher$MatchJob.run(ConsolePatternMatcher.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

```
   Compiling cc v1.0.18
   Compiling bitflags v1.0.3
   Compiling serde v1.0.70
   Compiling nodrop v0.1.12
   Compiling num-traits v0.2.5
   Compiling khronos_api v2.2.0
   Compiling cfg-if v0.1.4
   Compiling winapi-build v0.1.1
   Compiling memoffset v0.2.1
   Compiling lazy_static v1.0.2
   Compiling unicode-xid v0.1.0
   Compiling num-integer v0.1.39
   Compiling scopeguard v0.3.3
   Compiling token_store v0.1.2
   Compiling rand_core v0.2.1
   Compiling pkg-config v0.3.12
   Compiling rayon-core v1.4.1
   Compiling libc v0.2.42
   Compiling num-iter v0.1.37
   Compiling quote v0.3.15
   Compiling remove_dir_all v0.5.1
   Compiling rustc-serialize v0.3.24
   Compiling either v1.5.0
   Compiling rayon v1.0.2
   Compiling backtrace v0.2.3
   Compiling winapi v0.2.8
   Compiling unicode-xid v0.0.4
   Compiling void v1.0.2
   Compiling num-bigint v0.2.0
   Compiling num-rational v0.2.1
   Compiling piston-float v0.3.0
   Compiling adler32 v1.0.3
   Compiling nix v0.11.0
   Compiling nix v0.10.0
   Compiling linked-hash-map v0.5.1
   Compiling byteorder v1.2.4
   Compiling num-complex v0.2.0
   Compiling rustc-demangle v0.1.9
   Compiling fixedbitset v0.1.9
   Compiling traitobject v0.1.0
   Compiling fnv v1.0.6
   Compiling dtoa v0.4.3
   Compiling percent-encoding v1.0.1
   Compiling cgmath v0.16.1
   Compiling itoa v0.4.2
   Compiling quick-error v1.2.2
   Compiling color_quant v1.0.1
   Compiling lzw v0.10.0
   Compiling crossbeam v0.3.2
   Compiling unicode-width v0.1.5
   Compiling log-mdc v0.1.0
   Compiling antidote v1.0.0
   Compiling rust-oids v0.13.0 (/u01/home/nico/Projects/itadinanta/rust-oids)
   Compiling lazy_static v0.2.11
   Compiling bitflags v0.7.0
   Compiling vec_map v0.8.1
   Compiling approx v0.1.1
   Compiling bitflags v0.9.1
   Compiling bit-vec v0.5.0
   Compiling scoped_threadpool v0.1.9
   Compiling sample v0.10.0
   Compiling arrayvec v0.4.7
   Compiling xml-rs v0.7.0
   Compiling draw_state v0.8.0
   Compiling crossbeam-utils v0.2.2
   Compiling uuid v0.6.5
   Compiling proc-macro2 v0.4.9
   Compiling proc-macro2 v0.3.8
   Compiling dbghelp-sys v0.2.0
   Compiling kernel32-sys v0.2.2
   Compiling num_cpus v1.8.0
   Compiling rand v0.5.4
   Compiling rand v0.4.2
   Compiling iovec v0.1.2
   Compiling memmap v0.6.2
   Compiling time v0.1.40
   Compiling shared_library v0.1.9
   Compiling memchr v1.0.2
   Compiling dirs v1.0.2
   Compiling itertools v0.5.10
   Compiling itertools v0.7.8
   Compiling x11-dl v2.18.3
   Compiling libudev-sys v0.1.4
   Compiling portaudio v0.7.0
   Compiling libloading v0.5.0
   Compiling backtrace-sys v0.1.23
   Compiling miniz-sys v0.1.10
   Compiling cmake v0.1.32
   Compiling syn v0.10.8
   Compiling unreachable v0.1.1
   Compiling piston-viewport v0.3.0
   Compiling inflate v0.4.3
   Compiling yaml-rust v0.4.0
   Compiling stb_truetype v0.2.2
   Compiling deflate v0.7.18
   Compiling unsafe-any v0.4.2
   Compiling petgraph v0.4.12
   Compiling humantime v1.1.1
   Compiling gif v0.10.0
   Compiling getopts v0.2.18
   Compiling bit-set v0.5.0
   Compiling crossbeam-epoch v0.3.1
   Compiling quote v0.6.5
   Compiling wayland-scanner v0.12.5
   Compiling quote v0.5.2
   Compiling bytes v0.4.9
   Compiling rand v0.3.22
   Compiling osmesa-sys v0.1.2
   Compiling csv v0.15.0
   Compiling tempfile v3.0.3
   Compiling wrapped2d v0.4.0
   Compiling typemap v0.3.3
   Compiling daggy v0.5.0
   Compiling num-traits v0.1.43
   Compiling num-complex v0.1.43
   Compiling crossbeam-deque v0.2.0
   Compiling syn v0.14.7
   Compiling syn v0.13.11
   Compiling wayland-client v0.12.5
   Compiling wayland-protocols v0.12.5
   Compiling derivative v1.0.0
   Compiling ordered-float v0.5.0
   Compiling enum_primitive v0.1.1
   Compiling num-bigint v0.1.44
   Compiling chrono v0.4.5
   Compiling log v0.4.3
   Compiling serde_yaml v0.7.5
   Compiling serde_json v1.0.24
   Compiling ctrlc v3.1.1
   Compiling serde_derive v1.0.70
   Compiling num-derive v0.2.2
   Compiling dlib v0.4.1
   Compiling flate2 v1.0.2
   Compiling rusttype v0.4.3
   Compiling serde-value v0.5.2
   Compiling conrod_derive v0.1.2
   Compiling num-rational v0.1.42
   Compiling png v0.12.0
   Compiling gl_generator v0.9.0
   Compiling log v0.3.9
   Compiling gfx_core v0.8.2
   Compiling gilrs v0.6.1
   Compiling wayland-sys v0.12.5
   Compiling error-chain v0.5.0
   Compiling num v0.1.42
   Compiling num v0.2.0
   Compiling gl_generator v0.8.0
   Compiling gfx_gl v0.5.0
   Compiling gl v0.10.0
   Compiling pistoncore-input v0.20.0
   Compiling log4rs v0.8.0
   Compiling cpuprofiler v0.0.3
   Compiling jpeg-decoder v0.1.15
   Compiling pitch_calc v0.11.1
   Compiling glutin v0.12.2
   Compiling image v0.19.0
   Compiling wayland-kbd v0.13.1
   Compiling gfx v0.17.1
   Compiling wayland-window v0.13.3
   Compiling gfx_device_gl v0.15.3
   Compiling winit v0.10.0
   Compiling conrod v0.58.0
warning: trait objects without an explicit `dyn` are deprecated
   --> src/app/mod.rs:137:53
    |
137 |     fn apply(&self, world: &mut world::World, outbox: &Outbox) { self.ptr.read().unwrap().apply(world, outbox) }
    |                                                        ^^^^^^ help: use `dyn`: `dyn Outbox`
    |
    = note: #[warn(bare_trait_objects)] on by default

warning: trait objects without an explicit `dyn` are deprecated
   --> src/app/mod.rs:167:36
    |
167 |     fn systems(&mut self) -> Vec<Box<(systems::System + Send)>> {
    |                                       ^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn systems::System + Send`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/app/mod.rs:227:12
    |
227 |         outbox: &Outbox,
    |                  ^^^^^^ help: use `dyn`: `dyn Outbox`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/app/mod.rs:228:12
    |
228 |         apply: &(Fn(&mut systems::System, &mut world::World, &Outbox) + Sync),
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Fn(&mut systems::System, &mut world::World, &Outbox) + Sync`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/app/mod.rs:228:20
    |
228 |         apply: &(Fn(&mut systems::System, &mut world::World, &Outbox) + Sync),
    |                          ^^^^^^^^^^^^^^^ help: use `dyn`: `dyn systems::System`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/app/mod.rs:228:57
    |
228 |         apply: &(Fn(&mut systems::System, &mut world::World, &Outbox) + Sync),
    |                                                               ^^^^^^ help: use `dyn`: `dyn Outbox`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/app/mod.rs:234:66
    |
234 |     fn for_each_par_write(&mut self, world: &world::World, apply: &(Fn(&mut systems::System, &world::World) + Sync)) {
    |                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Fn(&mut systems::System, &world::World) + Sync`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/app/mod.rs:234:74
    |
234 |     fn for_each_par_write(&mut self, world: &world::World, apply: &(Fn(&mut systems::System, &world::World) + Sync)) {
    |                                                                             ^^^^^^^^^^^^^^^ help: use `dyn`: `dyn systems::System`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/messagebus/mod.rs:52:14
   |
52 |     accept: Box<Fn(&M) -> bool>,
   |                 ^^^^^^^^^^^^^^ help: use `dyn`: `dyn Fn(&M) -> bool`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/messagebus/mod.rs:67:38
   |
67 |     fn subscribe(&mut self, accept: Box<Fn(&M) -> bool>) -> Inbox<M>;
   |                                         ^^^^^^^^^^^^^^ help: use `dyn`: `dyn Fn(&M) -> bool`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/messagebus/mod.rs:96:38
   |
96 |     fn subscribe(&mut self, accept: Box<Fn(&M) -> bool>) -> Inbox<M> {
   |                                         ^^^^^^^^^^^^^^ help: use `dyn`: `dyn Fn(&M) -> bool`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/systems/ai.rs:41:55
   |
41 |     fn export(&self, world: &mut world::World, _outbox: &Outbox) {
   |                                                          ^^^^^^ help: use `dyn`: `dyn Outbox`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/systems/alife.rs:48:27
   |
48 |     fn update(&mut self, _: &AgentState, dt: Seconds) {
   |                              ^^^^^^^^^^ help: use `dyn`: `dyn AgentState`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/systems/alife.rs:53:54
   |
53 |     fn export(&self, world: &mut world::World, outbox: &Outbox) {
   |                                                         ^^^^^^ help: use `dyn`: `dyn Outbox`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend/systems/alife.rs:147:12
    |
147 |         outbox: &Outbox,
    |                  ^^^^^^ help: use `dyn`: `dyn Outbox`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/systems/animation.rs:23:27
   |
23 |     fn update(&mut self, _: &AgentState, dt: Seconds) {
   |                              ^^^^^^^^^^ help: use `dyn`: `dyn AgentState`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/systems/animation.rs:29:55
   |
29 |     fn export(&self, world: &mut world::World, _outbox: &Outbox) {
   |                                                          ^^^^^^ help: use `dyn`: `dyn Outbox`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend/systems/game.rs:103:27
    |
103 |     fn update(&mut self, _: &world::AgentState, dt: Seconds) {
    |                              ^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn world::AgentState`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend/systems/game.rs:139:54
    |
139 |     fn export(&self, world: &mut world::World, outbox: &Outbox) {
    |                                                         ^^^^^^ help: use `dyn`: `dyn Outbox`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend/systems/particle.rs:299:33
    |
299 |     emitters: HashMap<obj::Id, Box<Emitter>>,
    |                                    ^^^^^^^ help: use `dyn`: `dyn Emitter`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend/systems/particle.rs:430:27
    |
430 |     fn update(&mut self, _: &AgentState, dt: Seconds) {
    |                              ^^^^^^^^^^ help: use `dyn`: `dyn AgentState`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend/systems/particle.rs:438:55
    |
438 |     fn export(&self, world: &mut world::World, _outbox: &Outbox) {
    |                                                          ^^^^^^ help: use `dyn`: `dyn Outbox`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend/systems/physics.rs:128:31
    |
128 |     fn update(&mut self, state: &world::AgentState, dt_sec: Seconds) {
    |                                  ^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn world::AgentState`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend/systems/physics.rs:203:54
    |
203 |     fn export(&self, world: &mut world::World, outbox: &Outbox) {
    |                                                         ^^^^^^ help: use `dyn`: `dyn Outbox`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/systems/mod.rs:27:38
   |
27 |     fn update(&mut self, _world_state: &world::AgentState, _dt: Seconds) {}
   |                                         ^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn world::AgentState`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/systems/mod.rs:28:45
   |
28 |     fn export(&self, _: &mut world::World, _: &Outbox) {}
   |                                                ^^^^^^ help: use `dyn`: `dyn Outbox`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/systems/mod.rs:35:53
   |
35 |     fn apply(&self, world: &mut world::World, outbox: &Outbox) { self.export(world, outbox) }
   |                                                        ^^^^^^ help: use `dyn`: `dyn Outbox`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend/world/agent.rs:390:93
    |
390 |     pub fn new(id: Id, gender: u8, brain: &Brain, dna: &Dna, segments: Box<[Segment]>, timer: &Timer) -> Self {
    |                                                                                                ^^^^^ help: use `dyn`: `dyn Timer`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/world/phen.rs:22:90
   |
22 |     fn develop(&self, gen: &mut Genome, id: Id, initial_state: agent::InitialState, timer: &Timer) -> agent::Agent;
   |                                                                                             ^^^^^ help: use `dyn`: `dyn Timer`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/world/phen.rs:25:58
   |
25 | pub fn phenotype_of(agent_type: agent::AgentType) -> Box<Phenotype> {
   |                                                          ^^^^^^^^^ help: use `dyn`: `dyn Phenotype`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/world/phen.rs:43:90
   |
43 |     fn develop(&self, gen: &mut Genome, id: Id, initial_state: agent::InitialState, timer: &Timer) -> agent::Agent {
   |                                                                                             ^^^^^ help: use `dyn`: `dyn Timer`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/world/phen.rs:62:90
   |
62 |     fn develop(&self, gen: &mut Genome, id: Id, initial_state: agent::InitialState, timer: &Timer) -> agent::Agent {
   |                                                                                             ^^^^^ help: use `dyn`: `dyn Timer`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/world/phen.rs:87:90
   |
87 |     fn develop(&self, gen: &mut Genome, id: Id, initial_state: agent::InitialState, timer: &Timer) -> agent::Agent {
   |                                                                                             ^^^^^ help: use `dyn`: `dyn Timer`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend/world/phen.rs:173:90
    |
173 |     fn develop(&self, gen: &mut Genome, id: Id, initial_state: agent::InitialState, timer: &Timer) -> agent::Agent {
    |                                                                                             ^^^^^ help: use `dyn`: `dyn Timer`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend/world/phen.rs:376:30
    |
376 |     pub fn build(&self, timer: &Timer) -> Agent {
    |                                 ^^^^^ help: use `dyn`: `dyn Timer`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/world/swarm.rs:15:17
   |
15 |     phenotype: Box<phen::Phenotype>,
   |                    ^^^^^^^^^^^^^^^ help: use `dyn`: `dyn phen::Phenotype`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/world/swarm.rs:20:51
   |
20 |     pub fn new(agent_type: AgentType, phenotype: Box<phen::Phenotype>) -> Swarm {
   |                                                      ^^^^^^^^^^^^^^^ help: use `dyn`: `dyn phen::Phenotype`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/world/swarm.rs:68:91
   |
68 |     pub fn spawn(&mut self, genome: &mut Genome, initial_state: agent::InitialState, timer: &Timer) -> Id {
   |                                                                                              ^^^^^ help: use `dyn`: `dyn Timer`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/backend/world/swarm.rs:79:101
   |
79 |     pub fn rebuild(&mut self, id: Id, genome: &mut Genome, initial_state: agent::InitialState, timer: &Timer) -> Id {
   |                                                                                                        ^^^^^ help: use `dyn`: `dyn Timer`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend/world/mod.rs:152:47
    |
152 |     pub fn decay_to_resource(&mut self, outbox: &Outbox, transform: Transform, dna: &gen::Dna) -> obj::Id {
    |                                                  ^^^^^^ help: use `dyn`: `dyn Outbox`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend/world/mod.rs:164:39
    |
164 |     pub fn new_spore(&mut self, outbox: &Outbox, transform: Transform, dna: &gen::Dna) -> obj::Id {
    |                                          ^^^^^^ help: use `dyn`: `dyn Outbox`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend/world/mod.rs:176:41
    |
176 |     pub fn hatch_spore(&mut self, outbox: &Outbox, transform: Transform, dna: &gen::Dna) -> obj::Id {
    |                                            ^^^^^^ help: use `dyn`: `dyn Outbox`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend/world/mod.rs:259:42
    |
259 |     pub fn primary_fire(&mut self, outbox: &Outbox, bullet_speed: f32) {
    |                                             ^^^^^^ help: use `dyn`: `dyn Outbox`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/core/clock.rs:159:21
    |
159 |     pub fn new(timer: &Timer) -> Self {
    |                        ^^^^^ help: use `dyn`: `dyn Timer`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/core/clock.rs:191:39
    |
191 |     pub fn new(seconds: Seconds, timer: &Timer) -> Self {
    |                                          ^^^^^ help: use `dyn`: `dyn Timer`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/frontend/audio/multiplexer.rs:210:86
    |
210 |     fn signal_function(self, tone: Tone<T, S>, envelope: Envelope<T, S>, pan: S) -> Box<Fn(T) -> [S; CHANNELS]>
    |                                                                                         ^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Fn(T) -> [S; CHANNELS]`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/frontend/render/effects.rs:87:39
   |
87 |     pub fn new<F>(factory: &mut F, res: &resource::ResourceLoader<u8>, w: u16, h: u16) -> Result<PostLighting<R, C>>
   |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn resource::ResourceLoader<u8>`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/frontend/render/forward.rs:122:39
    |
122 |     pub fn new<F>(factory: &mut F, res: &resource::ResourceLoader<u8>, init: D) -> Result<ForwardLighting<R, C, D>>
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn resource::ResourceLoader<u8>`

warning: the item `texture` is imported redundantly
   --> src/frontend/ui/conrod_gfx.rs:621:21
    |
30  | use gfx::{self, texture, Factory, PipelineState, Resources};
    |                 ------- the item `texture` is already imported here
...
621 |         use gfx::{format, texture};
    |                           ^^^^^^^
    |
    = note: #[warn(unused_imports)] on by default

warning: trait objects without an explicit `dyn` are deprecated
   --> src/frontend/ui/conrod_ui.rs:110:42
    |
110 |                 let txt_with_label = |ids_iter: &mut Iterator<Item = &WidgetIdGroup>,
    |                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Iterator<Item = &WidgetIdGroup>`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/frontend/ui/conrod_ui.rs:135:45
    |
135 |                 let button_with_label = |ids_iter: &mut Iterator<Item = &WidgetIdGroup>,
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Iterator<Item = &WidgetIdGroup>`

warning: unused return value of `std::result::Result::<T, E>::is_ok` that must be used
   --> src/app/mod.rs:522:4
    |
522 |             world::persist::Serializer::load(&world_file, &mut self.world).is_ok();
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(unused_must_use)] on by default

warning: unused return value of `std::result::Result::<T, E>::is_ok` that must be used
  --> src/backend/messagebus/mod.rs:81:5
   |
81 |                 filter.sender.send(message.clone()).is_ok();
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused return value of `std::result::Result::<T, E>::is_ok` that must be used
   --> src/backend/world/mod.rs:352:3
    |
352 |         fs::create_dir_all(containing_dir).is_ok();
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused return value of `std::result::Result::<T, E>::is_ok` that must be used
   --> src/backend/world/mod.rs:361:3
    |
361 |         fs::create_dir_all(containing_dir).is_ok();
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    Finished dev [unoptimized + debuginfo] target(s) in 2m 09s
```

**Comment by akurtakov** [comment]
Hmm, it worked for me. Do you have rust-oids directly in your workspace? Or it's some kind of nested project? There is some issue with resolving the project so I have to figure what is different in your setup to support it proper.

**Comment by norru** [comment]
Directly in the workspace.

I also get the same outcome with all my projects and on all my workstations.

If it helps, I am running Corrosion snapshot on Debian/Devuan/Ubuntu.

**Comment by akurtakov** [comment]
Can you please share full paths to project and workspace?

**Comment by norru** [comment]
at home:

Project root: /home/nico/Projects/itadinanta/rust-oids

Workspace root: /home/nico/Workspaces/workspace_rust

Similar setup for all projects and workstations.

**Comment by akurtakov** [comment]
Can you put a breakpoint at ErrorLineMatcher.java#63 and let me know of the value of projectName variable?

**Comment by akurtakov** [comment]
Also can you try with newly created launch configuration? Is there a possibility your launch configuration is missing PROJECT attribute?

**Comment by norru** [comment]
Will do later today.

**Comment by norru** [comment]
`Project` is definitely correct in the Run configuration

Selection_201

**Comment by akurtakov** [comment]
Ah, it's debug and I was trying only Run configs.

**Comment by norru** [comment]
Uh? It's the same configuration for Rust.

**Comment by akurtakov** [comment]
https://github.com/eclipse/corrosion/pull/267 should fix it

**Comment by norru** [comment]
Cool! If you push it to Snapshots I'm gonna test it.

**Comment by norru** [comment]
To be fair I fail to see the point of separate Run/Debug configurations. in JDT there is no distinction, once one sets a config up it can be either used as Run... or Debug... launcher seamlessly.

**Comment by wjakobczyk** [comment]
For me it's working in console output when I run/debug project, but not when I just build (have a custom "cargo build" builder). The file names are not clickable there.

**Pull request merged**
