### PR TITLE
Issue #86 Set correct default locations on Windows

### PR DESCRIPTION
**Pull request by howlger**
Signed-off-by: Holger Voormann <eclipse@voormann.de>

### CODE REVIEW

**Comment by mickaelistria** [comment]
@howlger Why did you close this issue?

**Comment by LucasBullen** [comment]
I will assume due to using difference github signings as this PR failed the eclipse validation tool while #98, same content but different signing, did not

**Comment by mickaelistria** [comment]
Indeed, thanks @LucasBullen

**Comment by howlger** [comment]
@mickaelistria Yes, @LucasBullen is right. I signed off with my Eclipse instead of my GitHub e-mail address. My plan was to make a new pull request (#98) and delete this one. But you can only close pull requests and not delete them (at least I don't know how).

**Comment by mickaelistria** [comment]
Thanks @howlger . FWIW, we usually use a `git push --force myGithub HEAD:topicBranchWithPR` to create a new patch on an existing PR replacing previous one. Typical checks understand it and will run again. With that, it can prevent from creating multiple PRs.

**Pull request closed without merging**
