### PR TITLE
Added tentative logo mixin of Eclipse + Rust

### PR DESCRIPTION
**Pull request by norru**
I've smashed together the Eclipse and Rust logo to make up an icon which I've been using on https://gitter.im/eclipse_rust_development/Corrosion - I'm happy to have it used elsewhere if you like it.

### CODE REVIEW

**Comment by norru** [comment]
I have just submitted the ECA.

**Comment by mickaelistria** [comment]
There's already https://bugs.eclipse.org/bugs/attachment.cgi?id=272561 as project logo. I don't think we need.to change it.

**Comment by mickaelistria** [comment]
> Does it come in different resolutions?

I only have this file at hand. @LucasBullen created it IIRC, so maybe he still has some SVG or XCF file to share so we can create variations of the logo?

**Comment by mickaelistria** [comment]
I'm closing this one as we already have a logo.
@LucasBullen Do you have this logo in other formats (bigger size, SVG...) ?

**Comment by norru** [comment]
The official one has jagged edges when zoomed up.

**Pull request closed without merging**
