### PR TITLE
Templates for test cases and test modules

### PR DESCRIPTION
**Pull request by Boereck**
Added text templates for quick creation of test methods and test
modules.

Signed-off-by: Max Bureck <max.bureck@fokus.fraunhofer.de>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Do you know if there is an existing similar file in the rust toolchain or ecosystem we could reuse instead of building our own?

**Comment by Boereck** [comment]
I didn't know of a snippet library so far. I don't think any of the optional tools from the Rust toolchain provide such functionality. Now that you asked I searched for sources of snippets. It looks like the corrosion snippets are based on VS Codes, even though some modifications were done:
https://github.com/rust-lang-nursery/rls-vscode/blob/master/snippets/rust.json
I like their test snippet a bit better, so I'll adjust the one I proposed here this evening, when I have time. There are also a couple more templates (not yet in our file) we can also use, once adjusted to the corrosion format. But that can follow in a new PR.

I found another source for snippets: 
https://github.com/orhanbalci/rust-cookbook-snippets/tree/master/snippets 
But these are more file templates based on the Rust Cookbook, which itself is a bit dated. These templates also use external crates without specifying the version of the used crates. So I don't consider these very helpful.

**Comment by Boereck** [comment]
I hope the commit message is sufficient. I also included changes according to #158.

**Comment by mickaelistria** [comment]
Opened CQ  https://dev.eclipse.org/ipzilla/show_bug.cgi?id=17910


-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by Boereck** [comment]
Looks like the CQ is through, can we merge the PR, or has anything else to be done?

**Comment by mickaelistria** [comment]
All clear. Please merge.

**Pull request merged**
