### PR TITLE
Convert tests to JUnit 5.

### PR DESCRIPTION
**Pull request by akurtakov**
Signed-off-by: Alexander Kurtakov <akurtako@redhat.com>

### CODE REVIEW

**Comment by akurtakov** [comment]
@mickaelistria Local build finds no tests with both 1.7.0 and 2.0.0-SNAPHOT. In the patch it's 2.0.0 so you can work on a fix more easily.

**Comment by mickaelistria** [comment]
Passing the `-X` flag to Maven, we can see that the proper JUnit56Provider is used.
Adding `-Dtest=TestIDEIntegration` actually runs the test.
It looks like what's failing is the detection of the test classes. Does JUnit 5 use a different convention?

**Comment by akurtakov** [comment]
Weirdly https://git.eclipse.org/c/tycho/org.eclipse.tycho.git/tree/tycho-its/projects/surefire.junit54/bundle.test finds and run the tests. So detection works in some cases at least.

**Comment by mickaelistria** [comment]
The root pom.xml sets testClass to a class name that doesn'texist in the project. Removing testSuite/testClass makes the tests run.

**Comment by akurtakov** [comment]
Thanks Mickael. As it's pomless I ruled out the possibility for testClass being set too easily!

**Pull request merged**
