### PR TITLE
Troubleshooting guide

### PR DESCRIPTION
**Pull request by norru**
Signed-off-by: Nicola Orru <nigu.orru@gmail.com>

First pass of troubleshooting guide

### CODE REVIEW

**Comment by norru** [comment]
@mickaelistria There is no code change, what's up with the CI?

**Comment by mickaelistria** [comment]
Please try to rebase you change on top of master and `push --force` it to your branch; the build issue should vanish.

**Comment by norru** [comment]
Done

**Comment by mickaelistria** [comment]
Thanks!

**Pull request merged**
