### PR TITLE
Issue #94 Bug 3: Warning for missing rls

### PR DESCRIPTION
**Pull request by LucasBullen**
- Added a warning for whenever the rls is requested but missing
 - Added check for rustup and cargo paths actually being proper path by
checking their --verison

Signed-off-by: Lucas Bullen <lbullen@redhat.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=3

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=3

**Comment by LucasBullen** [comment]
Dismiss issue tracker references, not related

**Comment by mickaelistria** [comment]
Looks good to me.

**Pull request merged**
