### PR TITLE
Updated troubleshooting guide with references to 2019-03

### PR DESCRIPTION
**Pull request by norru**
Signed-off-by: Nicola Orru <nigu.orru@gmail.com>

- Minor documentation updates

### CODE REVIEW

**Comment by mickaelistria** [comment]
+1. Feel free to merge it.

**Comment by norru** [comment]
@mickaelistria Jenkins is failing though?

**Comment by mickaelistria** [comment]
The failure doesn't seem related.

**Comment by norru** [comment]
Okeydokey, done.

**Pull request merged**
